name: Linting Pipeline

on: [pull_request]

jobs:
  lint-backend:
    name: Backend Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8 on Backend
        run: |
          cd backend
          flake8

  lint-frontend:
    name: Frontend Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install ESLint and plugins
        run: |
          npm install eslint --save-dev

      - name: Run ESLint on Frontend
        run: |
          cd frontend
          npx eslint .
